version: "3"
services:
  ucsc_spectral_pipeline_local:
    build:
      context: .
    volumes:
      - ../:/home/UCSC_spectral_pipeline
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../extra_files/disp.cl:/home/iraf/disp.cl
      - ../login.cl:/etc/iraf/login.cl
    environment:
      - DISPLAY=host.docker.internal:0
      - UCSC_SPECPIPE=/home/UCSC_spectral_pipeline
      - PIPELINE=/home/UCSC_spectral_pipeline/spectral_reduction
  ucsc_spectral_pipeline_latest:
    image: ghcr.io/astrophpeter/ucsc_spectral_pipeline:latest
    volumes:
      - ../:/home/UCSC_spectral_pipeline
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../extra_files/disp.cl:/home/iraf/disp.cl
      - ../login.cl:/etc/iraf/login.cl
    environment:
      - DISPLAY=host.docker.internal:0
      - UCSC_SPECPIPE=/home/UCSC_spectral_pipeline
      - PIPELINE=/home/UCSC_spectral_pipeline/spectral_reduction
