version: "3"
services:
  ucsc_spectral_pipeline_base:
    build:
      context: .
    volumes:
      - ../:/home/UCSC_spectral_pipeline
      - $SOCKET:/tmp/.X11-unix
      - $IRAF_DISP_FILE:/etc/iraf/disp.cl
      - $IRAF_LOGIN_FILE:/etc/iraf/login.cl
      - $DATA_VOLUME:/home/data/
    env_file:
      - $PATH_TO_ENV
  ucsc_spectral_pipeline_latest:
    extends:
      file: docker-compose.yml
      service: ucsc_spectral_pipeline_base
    image: $DOCKER_IMAGE


